include:
  - board: seeed_xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart # Enables ZMK Studio USB communication
  - board: seeed_xiao_ble
    shield: totem_right
# there is no settingsreset (needed) for the XIAO
